# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox1 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox1.setFont(font)
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber1 = QtWidgets.QLCDNumber(self.groupBox1)
        self.lcdNumber1.setAutoFillBackground(True)
        self.lcdNumber1.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber1.setObjectName("lcdNumber1")
        self.horizontalLayout.addWidget(self.lcdNumber1)
        self.horizontalLayout_3.addWidget(self.groupBox1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.groupBox2 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox2.setFont(font)
        self.groupBox2.setFlat(True)
        self.groupBox2.setObjectName("groupBox2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcdNumber2 = QtWidgets.QLCDNumber(self.groupBox2)
        self.lcdNumber2.setAutoFillBackground(True)
        self.lcdNumber2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.horizontalLayout_2.addWidget(self.lcdNumber2)
        self.horizontalLayout_3.addWidget(self.groupBox2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(117, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.recordCheckBox = QtWidgets.QCheckBox(self.widget_2)
        self.recordCheckBox.setObjectName("recordCheckBox")
        self.horizontalLayout_4.addWidget(self.recordCheckBox)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FS2012 Flow Sensors"))
        self.groupBox1.setTitle(_translate("MainWindow", "Sensor 1 (L/min)"))
        self.groupBox2.setTitle(_translate("MainWindow", "Sensor 2 (L/min)"))
        self.recordCheckBox.setText(_translate("MainWindow", "Record"))

